global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']   
  - job_name: 'node-exporter'
    scrape_interval: 5s
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - source_labels: [__meta_kubernetes_node_label_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__address__]
        target_label: __address__
        replacement: '${1}:9100'
        regex: (.+)
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_prometheus_io_scrape]
        action: keep
        regex: true
  - job_name: 'kubernetes-state-metrics'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_prometheus_io_cluster]
        action: keep
        regex: true
  - job_name: 'kubernetes-cadvisor'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_prometheus_io_cadvisor]
        action: keep
        regex: true
  - job_name: 'kubelet'
    kubernetes_sd_configs:
      - role: 'node'
    relabel_configs:
      - source_labels: [__meta_kubernetes_node_name]
        target_label: node