name: Deploy Infrastructure

on:
    pull_request:
      types:
        - opened
        - synchronize
        - reopened
        - closed


env:
    working-directory: "terraform"


jobs:
  tf_fmt:
    name: Deploy Site
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3
      
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: us-east-1
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
            terraform_version: latest
            terraform_wrapper: false # This is recommended so the `terraform show` command outputs valid JSON

    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: path/to/terraform/root
    - name: Pluralith Init
      uses: Pluralith/actions/init@v1.4.0
      with:
        api-key: ${{ secrets.PLURALITH_API_KEY }}
        terraform-path: "${{ env.working-directory }}/application"

# Run Pluralith to generate an infrastructure diagram and comment body
    - name: Pluralith Run
      uses: Pluralith/actions/run@v1.4.0
      with:
        terraform-command: "plan"
        terraform-path: "${{ env.working-directory }}/application"
        show-changes: true
        show-drift: true
    
    # Post the generated diagram as a GitHub comment
    - name: Pluralith Comment
      uses: Pluralith/actions/comment@v1.4.0
      with:
        terraform-path: "${{ env.working-directory }}/application"
    
    
    
  
    - name: Terraform validate
      id: validate
      run: terraform validate
    - name: Terraform Plan
      id: plan
      run: terraform plan -out=tfplan -no-color -input=false
      continue-on-error: true
    
    
